/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booking.tiket.bioskop;

/**
 *
 * @author Lenovo
 */
public class TempatDuduk extends javax.swing.JFrame {

    /**
     * Creates new form TempatDuduk
     */
    public TempatDuduk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        previousbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        B3box = new javax.swing.JCheckBox();
        B4box = new javax.swing.JCheckBox();
        B5box = new javax.swing.JCheckBox();
        B6box = new javax.swing.JCheckBox();
        B7box = new javax.swing.JCheckBox();
        B8box = new javax.swing.JCheckBox();
        C8box = new javax.swing.JCheckBox();
        C6box = new javax.swing.JCheckBox();
        C5box = new javax.swing.JCheckBox();
        C1box = new javax.swing.JCheckBox();
        C4box = new javax.swing.JCheckBox();
        C3box = new javax.swing.JCheckBox();
        A1box = new javax.swing.JCheckBox();
        C2box = new javax.swing.JCheckBox();
        A2box = new javax.swing.JCheckBox();
        C7box = new javax.swing.JCheckBox();
        A3box = new javax.swing.JCheckBox();
        A5box = new javax.swing.JCheckBox();
        D1box = new javax.swing.JCheckBox();
        D5box = new javax.swing.JCheckBox();
        A4box = new javax.swing.JCheckBox();
        D4box = new javax.swing.JCheckBox();
        A7box = new javax.swing.JCheckBox();
        D2box = new javax.swing.JCheckBox();
        A6box = new javax.swing.JCheckBox();
        D3box = new javax.swing.JCheckBox();
        A8box = new javax.swing.JCheckBox();
        D7box = new javax.swing.JCheckBox();
        B1box = new javax.swing.JCheckBox();
        D6box = new javax.swing.JCheckBox();
        B2box = new javax.swing.JCheckBox();
        D8box = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PILIH TEMPAT DUDUK");

        jButton1.setText("SELANJUTNYA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        previousbutton.setText("KEMBALI");

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        B3box.setText("B3");
        B3box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3boxActionPerformed(evt);
            }
        });

        B4box.setText("B4");
        B4box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4boxActionPerformed(evt);
            }
        });

        B5box.setText("B5");
        B5box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5boxActionPerformed(evt);
            }
        });

        B6box.setText("B6");
        B6box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6boxActionPerformed(evt);
            }
        });

        B7box.setText("B7");
        B7box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7boxActionPerformed(evt);
            }
        });

        B8box.setText("B8");
        B8box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8boxActionPerformed(evt);
            }
        });

        C8box.setText("C8");
        C8box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8boxActionPerformed(evt);
            }
        });

        C6box.setText("C6");
        C6box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6boxActionPerformed(evt);
            }
        });

        C5box.setText("C5");
        C5box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5boxActionPerformed(evt);
            }
        });

        C1box.setText("C1");
        C1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1boxActionPerformed(evt);
            }
        });

        C4box.setText("C4");
        C4box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4boxActionPerformed(evt);
            }
        });

        C3box.setText("C3");
        C3box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3boxActionPerformed(evt);
            }
        });

        A1box.setText("A1");
        A1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1boxActionPerformed(evt);
            }
        });

        C2box.setText("C2");
        C2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2boxActionPerformed(evt);
            }
        });

        A2box.setText("A2");
        A2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2boxActionPerformed(evt);
            }
        });

        C7box.setText("C7");
        C7box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7boxActionPerformed(evt);
            }
        });

        A3box.setText("A3");
        A3box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3boxActionPerformed(evt);
            }
        });

        A5box.setText("A5");
        A5box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5boxActionPerformed(evt);
            }
        });

        D1box.setText("D1");
        D1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1boxActionPerformed(evt);
            }
        });

        D5box.setText("D5");
        D5box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5boxActionPerformed(evt);
            }
        });

        A4box.setText("A4");
        A4box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4boxActionPerformed(evt);
            }
        });

        D4box.setText("D4");
        D4box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4boxActionPerformed(evt);
            }
        });

        A7box.setText("A7");
        A7box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7boxActionPerformed(evt);
            }
        });

        D2box.setText("D2");
        D2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2boxActionPerformed(evt);
            }
        });

        A6box.setText("A6");
        A6box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6boxActionPerformed(evt);
            }
        });

        D3box.setText("D3");
        D3box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3boxActionPerformed(evt);
            }
        });

        A8box.setText("A8");
        A8box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A8boxActionPerformed(evt);
            }
        });

        D7box.setText("D7");
        D7box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7boxActionPerformed(evt);
            }
        });

        B1box.setText("B1");
        B1box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1boxActionPerformed(evt);
            }
        });

        D6box.setText("D6");
        D6box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6boxActionPerformed(evt);
            }
        });

        B2box.setText("B2");
        B2box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2boxActionPerformed(evt);
            }
        });

        D8box.setText("D8");
        D8box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D8boxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("LAYAR BIOSKOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(C1box)
                            .addComponent(D1box)
                            .addComponent(B1box)
                            .addComponent(A1box))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(C2box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C3box))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(B2box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B3box)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C4box)
                                    .addComponent(B4box)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(A2box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A3box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A4box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(D2box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(D3box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D4box)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(A5box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A6box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A7box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A8box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(D5box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(D6box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D7box)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D8box))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(C5box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C6box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C7box))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(B5box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B6box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B7box)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B8box)
                                    .addComponent(C8box)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1box)
                    .addComponent(A2box)
                    .addComponent(A3box)
                    .addComponent(A4box)
                    .addComponent(A5box)
                    .addComponent(A6box)
                    .addComponent(A7box)
                    .addComponent(A8box))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B8box)
                    .addComponent(B7box)
                    .addComponent(B6box)
                    .addComponent(B5box)
                    .addComponent(B4box)
                    .addComponent(B3box)
                    .addComponent(B2box)
                    .addComponent(B1box))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D1box)
                            .addComponent(D2box)
                            .addComponent(D3box)
                            .addComponent(D4box)
                            .addComponent(D5box)
                            .addComponent(D6box)
                            .addComponent(D7box)
                            .addComponent(D8box)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C2box)
                            .addComponent(C1box)
                            .addComponent(C3box)
                            .addComponent(C4box)
                            .addComponent(C5box)
                            .addComponent(C6box)
                            .addComponent(C7box)
                            .addComponent(C8box))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(previousbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(previousbutton))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void A1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1boxActionPerformed

    private void A2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2boxActionPerformed

    private void A3boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3boxActionPerformed

    private void A5boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5boxActionPerformed

    private void A4boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4boxActionPerformed

    private void A7boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A7boxActionPerformed

    private void A6boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6boxActionPerformed

    private void A8boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A8boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A8boxActionPerformed

    private void B1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1boxActionPerformed

    private void B2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2boxActionPerformed

    private void B3boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3boxActionPerformed

    private void B4boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4boxActionPerformed

    private void B5boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5boxActionPerformed

    private void B6boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6boxActionPerformed

    private void B7boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B7boxActionPerformed

    private void B8boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B8boxActionPerformed

    private void C8boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C8boxActionPerformed

    private void C6boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C6boxActionPerformed

    private void C5boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C5boxActionPerformed

    private void C1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1boxActionPerformed

    private void C4boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C4boxActionPerformed

    private void C3boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C3boxActionPerformed

    private void C2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2boxActionPerformed

    private void C7boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C7boxActionPerformed

    private void D1boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1boxActionPerformed

    private void D5boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D5boxActionPerformed

    private void D4boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D4boxActionPerformed

    private void D2boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2boxActionPerformed

    private void D3boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3boxActionPerformed

    private void D7boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D7boxActionPerformed

    private void D6boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D6boxActionPerformed

    private void D8boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D8boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D8boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempatDuduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempatDuduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempatDuduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempatDuduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempatDuduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1box;
    private javax.swing.JCheckBox A2box;
    private javax.swing.JCheckBox A3box;
    private javax.swing.JCheckBox A4box;
    private javax.swing.JCheckBox A5box;
    private javax.swing.JCheckBox A6box;
    private javax.swing.JCheckBox A7box;
    private javax.swing.JCheckBox A8box;
    private javax.swing.JCheckBox B1box;
    private javax.swing.JCheckBox B2box;
    private javax.swing.JCheckBox B3box;
    private javax.swing.JCheckBox B4box;
    private javax.swing.JCheckBox B5box;
    private javax.swing.JCheckBox B6box;
    private javax.swing.JCheckBox B7box;
    private javax.swing.JCheckBox B8box;
    private javax.swing.JCheckBox C1box;
    private javax.swing.JCheckBox C2box;
    private javax.swing.JCheckBox C3box;
    private javax.swing.JCheckBox C4box;
    private javax.swing.JCheckBox C5box;
    private javax.swing.JCheckBox C6box;
    private javax.swing.JCheckBox C7box;
    private javax.swing.JCheckBox C8box;
    private javax.swing.JCheckBox D1box;
    private javax.swing.JCheckBox D2box;
    private javax.swing.JCheckBox D3box;
    private javax.swing.JCheckBox D4box;
    private javax.swing.JCheckBox D5box;
    private javax.swing.JCheckBox D6box;
    private javax.swing.JCheckBox D7box;
    private javax.swing.JCheckBox D8box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton previousbutton;
    // End of variables declaration//GEN-END:variables
}
